CITY_PETROVICH = {
    'moscow': 'msk',
    'arkhangelsk': 'arkh',
    'astrakhan': 'astrh',
    'novgorod': 'nvr',
    'vladimir': 'vld',
    'volzhskiy': 'volzh',
    'vyborg': 'vbg',
    'gatchina': 'gtn',
    'gubkin': 'gbkn',
    'zheleznogorsk': 'zhelez',
    'i-ola': 'iola',
    'kazan': 'kzn',
    'kaluga': 'klg',
    'kingisepp': 'kgs',
    'kirov': 'krv',
    'kursk': 'krsk',
    'lipetsk': 'lipck',
    'luga': 'lug',
    'magnitogorsk': 'mgnt',
    'naberezhnye-chelny': 'nabchel',
    'nizhnevartovsk': 'nizhvar',
    'nizhniy-novgorod': 'nizhnov',
    'nizhniy-tagil': 'tagil',
    'orel': 'orl',
    'pervouralsk': 'pervour',
    'petrozavodsk': 'pzv',
    'pskov': 'pskv',
    'ryazan': 'rzn',
    'stary-oskol': 'oskol',
    'syktyvkar': 'sktv',
    'tver': 'tvr',
    'tobolsk': 'tbl',
    'tula': 'tul',
    'cheboksary': 'cheb',
    'engels': 'engl',
    'petrovich': 'spb',  # Санкт-Петербург без поддомена
}
