"""Remove all caracter varying constraints (50 and 250 symbols constraints gone)

Revision ID: 8e33fae909d4
Revises: 031ca2e65db0
Create Date: 2023-11-29 20:27:58.071926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e33fae909d4'
down_revision: Union[str, None] = '031ca2e65db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
