"""Alter model Product, remove 250 symbols constraint from title and url

Revision ID: 031ca2e65db0
Revises: 6840c1e4d00b
Create Date: 2023-11-29 20:15:18.057228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031ca2e65db0'
down_revision: Union[str, None] = '6840c1e4d00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
