"""Alter model City, removing 'unique' flag from table name (title)

Revision ID: 6840c1e4d00b
Revises: 8695e3753f44
Create Date: 2023-11-29 19:58:19.982605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6840c1e4d00b'
down_revision: Union[str, None] = '8695e3753f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_title_key', 'cities', type_='unique')
    op.create_unique_constraint(None, 'cities', ['id'])
    op.create_unique_constraint(None, 'prices', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'shops', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'prices', type_='unique')
    op.drop_constraint(None, 'cities', type_='unique')
    op.create_unique_constraint('cities_title_key', 'cities', ['title'])
    # ### end Alembic commands ###
